// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxvergpcuedqodvjjkgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4dmVyZ3BjdWVkcW9kdmpqa2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNTcyNDgsImV4cCI6MjA3NDYzMzI0OH0.ANv7yFAp-dAmn_p-ZlGXtpqABwBbb7z4Z-W6or3HmuI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
